Add container for fpm and nginx combined. Changed conf.d directory to config. Install acpu extension. Run supervisord for combined fpm-nginx under www-data.

diff --git a/7.3/alpine/fpm-nginx/Dockerfile b/7.3/alpine/fpm-nginx/Dockerfile
--- a/7.3/alpine/fpm-nginx/Dockerfile
+++ b/7.3/alpine/fpm-nginx/Dockerfile
@@ -1,75 +1,41 @@
-FROM php:7.3-fpm-alpine
+FROM drsdre/php-laravel:7.3-fpm-alpine
 
 MAINTAINER Andre Schuurman <docker@drsdre.org>
 
-LABEL Description="This image contains PHP 7.3 on alpine OS with extension needed for running Laravel applications" Vendor="Andre Schuurman" Version="7.3-fpm-alpine"
-
-ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="0" \
-    PHP_OPCACHE_MAX_ACCELERATED_FILES="10000" \
-    PHP_OPCACHE_MEMORY_CONSUMPTION="192" \
-    PHP_OPCACHE_MAX_WASTED_PERCENTAGE="10"
+LABEL Description="This image contains PHP 7.3 with FPM and Ngninx on alpine OS with extension needed for running Laravel applications" Vendor="Andre Schuurman" Version="7.3-fpm_nginx-alpine"
 
 # Install production dependencies
+# install nginx (copied from official nginx Dockerfile)
+RUN NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+	found=''; \
+	for server in \
+		ha.pool.sks-keyservers.net \
+		hkp://keyserver.ubuntu.com:80 \
+		hkp://p80.pool.sks-keyservers.net:80 \
+		pgp.mit.edu \
+	; do \
+		echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+		apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+	done; \
+	test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+	echo "deb http://nginx.org/packages/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
+	# echo "deb-src http://nginx.org/packages/debian/ stretch nginx" >> /etc/apt/nginx.list \
+	&& apt-get update \
+	&& apt-get install --no-install-recommends --no-install-suggests -y \
+						nginx=${NGINX_VERSION} \
+						nginx-module-xslt=${NGINX_VERSION} \
+						nginx-module-geoip=${NGINX_VERSION} \
+						nginx-module-image-filter=${NGINX_VERSION} \
+						nginx-module-njs=${NJS_VERSION} \
+						gettext-base \
+	&& rm -rf /var/lib/apt/lists/*
+
+# forward nginx request and error logs to docker log collector
+RUN ln -sf /dev/stdout /var/log/nginx/access.log \
+	&& ln -sf /dev/stderr /var/log/nginx/error.log
+
 RUN apk add --update --no-cache \
-    bash \
-    curl \
     supervisor
-    #g++ \
-    #gcc \
-    #git \
-    #imagemagick \
-    #icu-libs \
-    #libevent \
-    #libintl \
-    #libxslt \
-    #libzip \
-    #make \
-    #mysql-client \
-    #nodejs \
-    #nodejs-npm \
-    #yarn \
-    #openssh-client \
-    #postgresql-libs \
-    #rsync
-
-ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
-
-RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
-    install-php-extensions \
-    bcmath \
-    exif \
-    gd \
-    gettext \
-    igbinary \
-    imagick \
-    intl \
-    opcache \
-    pcntl \
-    pdo_mysql \
-    pdo_pgsql \
-    redis \
-    sockets \
-    xsl \
-    yaml \
-    zip
-
-# make sockets extension load first
-RUN cd /usr/local/etc/php/conf.d/ && \
-    mv docker-php-ext-sockets.ini 1-docker-php-ext-sockets.ini
-
-COPY config/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
-
-# Change memory limit
-RUN echo 'memory_limit = 2G ' >> /usr/local/etc/php/php.ini
-
-# make the entrypoint executable
-RUN chmod a+x /usr/local/bin/docker-php-entrypoint
-
-# restrict console commands execution for web scripts
-RUN chmod o-rx /bin/busybox /usr/bin/curl /usr/local/bin/pecl
-
-# Cleanup
-RUN rm -rf /tmp/*  ~/.pearrc
 
 # Configure nginx
 COPY config/nginx.conf /etc/nginx/nginx.conf
